### ISSUE TITLE
[Feature Request] Add Tap-to-Play Functionality for Synchronized Lyrics

### ISSUE THREAD

**Issue by justpanchi** [DJDoubleD/refreezer#15]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

I am unable to jump to specific parts of a song directly from the synchronized lyrics. When viewing lyrics that are synced with the song, it would greatly enhance the user experience if I could tap on a specific line and have the song start playing from that exact moment. Currently, I have to manually scrub through the song to find the desired part.

---

## **Describe the solution you'd like**

I would like to have the ability to tap on any line of the synchronized lyrics, and the song should automatically start playing from the corresponding timestamp. This would make it much easier to replay specific parts of a song and would create a more interactive and seamless experience for users who follow along with lyrics.

---

## **Describe alternatives you've considered**

An alternative could be to display timestamps next to each lyric line so that users can manually scrub to the desired timestamp, but this is less efficient and not as user-friendly. Another option could be a mini-controller that appears when a line of lyrics is selected, allowing the user to play from that point. However, a direct tap-to-play feature is the most intuitive solution.

---

### **Additional context**

This feature would be especially useful for users who like to study lyrics, practice singing along, or just quickly jump to their favorite part of a song.

**Comment by DJDoubleD** [comment]
Hey @justpanchi :)

I have actually thought about this feature myself quite a few times, thanks for writing it out.
