### ISSUE TITLE
[Feature Request] Since the application is developed using Flutter, which is a cross-platform framework, is it possible to obtain a desktop version for Windows, Linux, or macOS?

### ISSUE THREAD

**Issue by abderrahmanebenhalima** [DJDoubleD/refreezer#17]
# **🚀 Feature Request**
Since the application is developed using Flutter, which is a cross-platform framework, is it possible to obtain a desktop version for Windows, Linux, or macOS?

**Comment by DJDoubleD** [comment]
Even though Flutter is used, there is a lot of android specific packages and native java code being used.
Porting the app to desktop would require so many changes that it would almost be a new app. (The original freezer app also had a separate desktop app that didn't use flutter)

Therefore, ReFreezer will remain Android only.
