### ISSUE TITLE
[Bug] Lyrics Button Active in Landscape Mode for Tracks with No Lyrics

### ISSUE THREAD

**Issue by justpanchi** [DJDoubleD/refreezer#19]
# **🐞 Bug Report**

## **Describe the bug**
In the music player screen, when a track has no lyrics, the lyrics button is usually greyed out and unresponsive. However, when the device is rotated to landscape mode, the button becomes active and can be pressed, resulting in an empty lyrics screen being displayed.

---

### **Is this a regression?**
No, this bug has been present in previous versions of the app, but it was only noticed recently.

---

### **To Reproduce**

1. Open the music player app.
2. Select a track that does not have lyrics.
3. Ensure the device is in portrait mode; verify that the lyrics button is greyed out.
4. Rotate the device to landscape mode.
5. Press the now-active lyrics button.
6. Observe that an empty lyrics screen is displayed.

---

### **Expected behaviour**
The lyrics button should remain greyed out and unresponsive when there are no lyrics available, regardless of the device orientation.

---

### **Screenshots**
![Portrait](https://github.com/user-attachments/assets/4e5cd1b7-8dbe-4559-bc60-d719c539a92e)
![Landscape](https://github.com/user-attachments/assets/ae5513d1-0c5f-40e6-80a0-074fcd0f4e3c)
![Landscape_Lyrics](https://github.com/user-attachments/assets/28d77b8c-dfb4-4ba2-aab8-20b97b28a5b4)

---

### **Additional context**
This issue appears to be related to how the app handles orientation changes and the availability of lyrics.

**Comment by DJDoubleD** [comment]
Oops, forgot to use the lyrics button widget in the horizontal view...

**Comment by monacoandco2311** [comment]
Bonjour,
Je viens de découvrir cette app, elle est vraiment formidable, mon seul problème est que le micro pour les lyrics est toujours grisé, j'ai cherché dans les paramètres mais rien trouvé.
Merci pour votre aide
