### ISSUE TITLE
Community

### ISSUE THREAD

**Issue by EuriNaiz** [DJDoubleD/refreezer#2]
Hi, are there any community on TG to join? Some users have mentioned this project on our Freezer Spanish community.

**Comment by DJDoubleD** [comment]
Hi, I hope my app is working well for you.
I don't have a dedicated TG channel, but if you are looking for other users to engage with, you can join the [TG group](https://t.me/firehawk52official/37318/73750) where I first published the public release of my project (please read and respect the [group's rules](https://t.me/firehawk52official/1/62667) when entering, thx :) ).

Please keep in mind that ReFreezer is just my personal hobby project and all development is "best effort".
If you find any bugs or interesting (realistic) feature requests, please create issues for them here on github so I can easily keep track of them.
I'll try to handle bugs with priority.
