### ISSUE TITLE
[Bug] Setting = FLAC Download, Real Download = 128kbs MP3 --> Help needed

### ISSUE THREAD

**Issue by Justice5656** [DJDoubleD/refreezer#22]
# **🐞 Bug Report**

*I set the download settings to FLAC but the downloaded files are all 128kbps MP3.

I tried with Family ARL and also with Premium ARL.

Is it a but or just a feature with is not possible but shown in the App?

Thanks for your help

**Comment by DJDoubleD** [comment]
Closing due to lack of response.
