### ISSUE TITLE
[Bug] Almacenamiento 

### ISSUE THREAD

**Issue by Mavrok** [DJDoubleD/refreezer#24]
# **🐞 Bug Report**

## **Describe the bug**

*Cuando elijo la opción de descargar en el almacenamiento externo da un error de descarga.

---

### **Is this a regression?**

---

### **To Reproduce**

1.
2.
3.
4.

---

### **Expected behaviour**

*

---

### **Screenshots**

---

### **Additional context**

*

**Comment by DJDoubleD** [comment]
1. English only please!
2. In the readme, I clearly indicated:
  
    > Support downloading to external storage (sdcard) for android 11 and up

    So if you are using a device with android 10 or below, downloading to sdcard isn't supported.
    If you are using android 11 or above, make sure you allowed storage permissions when the app asked. If you still receive an error, please add the steps to reproduce to this issue (in English)

**Comment by DJDoubleD** [comment]
Closing due to lack of response
