### ISSUE TITLE
[Bug] Songs aren't playing in FLAC 

### ISSUE THREAD

**Issue by Chrinkly** [DJDoubleD/refreezer#25]
# **🐞 Bug Report**

## **Describe the bug**

* Switched the Mobile&Wifi streaming from 128kbps to FLAC and all the songs I play only does 128kpbs and not FLAC. Why is that?

**Comment by DJDoubleD** [comment]
You need a HIFI account in order to be able to stream in FLAC quality.
Closing because the question (and answer) is most likely the same as #22
