### ISSUE TITLE
[Enhancement]  Adaptive App Icon (Monet/Material You)

### ISSUE THREAD

**Issue by justpanchi** [DJDoubleD/refreezer#26]
# **🚀 Enhancement Request**

## **Is your enhancement request related to a problem? Please describe.**

This request is not related to a problem but is a visual UI/UX enhancement. It would be great if the app icon supported Material You design, allowing it to integrate with the dynamic theming introduced in Android 12. This change is purely cosmetic and not necessary for the app's functionality.

---

## **Describe the solution you'd like**

I would like the app icon to support Material You, enabling it to adapt to the system's dynamic color theming on Android 12 and above. This would enhance the visual consistency of the app with the overall system design on newer devices.

---

## **Describe alternatives you've considered**

The current static icon works fine, but supporting Material You would improve the app’s appearance on devices running Android 12 or higher, giving it a more modern look.

---

### **Additional context**

- This is strictly a visual enhancement and does not impact the app’s functionality.

- Older Android versions can still use the current static icon without any issues.

- Adding support for Material You will improve the app's integration with newer Android design standards.

**Comment by DJDoubleD** [comment]
Created a monochrome drawable version of the launcher icon, which is now used when themed icons is enabled (Material You).
A few illustrative examples:

![Icon_Example_blue](https://github.com/user-attachments/assets/b40e8278-1d5d-4e75-8158-46a9c2f0d6d2)
![Icon_Example_green](https://github.com/user-attachments/assets/6355877f-2bdf-49d1-a31a-8d6dc7083316)
![Icon_Example_grey](https://github.com/user-attachments/assets/f0d65a46-2c49-44ae-907a-427482fcb382)
![Icon_Example_orange](https://github.com/user-attachments/assets/af7825ed-e0d1-4292-b33b-b3b244ea604b)
![Icon_Example_yellow](https://github.com/user-attachments/assets/90058eae-5ab7-47a9-a06e-5269cb927c7f)
![Icon_Example_red](https://github.com/user-attachments/assets/4a553fe0-b09d-4d62-9029-13524cf423f9)
