### ISSUE TITLE
[Bug] App doesn't load

### ISSUE THREAD

**Issue by Gamma8219** [DJDoubleD/refreezer#33]
# **🐞 Bug Report**

## **Describe the bug**

*Hello, the app hasn't started up for about 30 minutes, I left it playing music and it stopped, it didn't do anything else. I closed the app and it didn't even open anymore. I am with version 0.7.14

**Comment by DJDoubleD** [comment]
I've never encountered this issue myself, so don't know how to reproduce it.
Steps to try:

1. Did you remove the app from background tasks before restarting?
2. If step 1 doesn't help, open Settings => Apps => ReFreezer and clear cache
3. If step 2 still doesn't help, try clearing data as well

After step 2 and/or 3, you'll need to log in again and redownload any offline content.

**Comment by DJDoubleD** [comment]
> Hi, I did what you suggested and it works now. Thank you so much

For future reference, could you please clarify which of the 3 steps you had to do to fix it?
Feel free to close the issue on your answer, thanks.

**Comment by Gamma8219** [comment]
Hi, number 2.
