### ISSUE TITLE
[Bug] Unable to compile

### ISSUE THREAD

**Issue by PetitPrinc3** [DJDoubleD/refreezer#37]
# **🐞 Bug Report**

## **Describe the bug**
I am not able to compile the app following the provided steps as environment variables are missing. 

### **To Reproduce**

1. Clone the repo
2. Clone each submodule separately because git submodule update won't work
3. Run "run_build_runner.ps1"

### **Screenshots**

![image](https://github.com/user-attachments/assets/b478c9b6-5797-4554-b330-f756eeff5f59)

### **Additional context**

Because of this issue, it is not possible to compile the apk afterwards. (missing env.g.dart)  
I tried a few things to no avail, I always end up not being able to compile when running flutter build.  
I know I should use my "own" keys, but I am failing to understand how to provide them. I think there is a missing step in this regard.

**Comment by DJDoubleD** [comment]
I updated the ReadMe to include the instructions you're missing.
You'll need to find/create the needed keys and secrets yourself, as I'm not including these in the public repo.
They might be found in other repos of Deezer download tools.
LastFM values can be made with your own LastFM account.

**Comment by PetitPrinc3** [comment]
Thank you for your work and quick reply. However, the issue had more to do with api keys than the signing keys.

### 🪛 Fix  
Create a .env file in /lib containing :
```# Deezer API credentials (same as streamrip & Orpheus)
deezerClientId = '<REDACTED>';
deezerClientSecret = '<REDACTED>';
lastFmApiKey = "<REDACTED>"
lastFmApiSecret = "<REDACTED>"```

**Comment by Verizane** [comment]
> I updated the ReadMe to include the instructions you're missing. You'll need to find/create the needed keys and secrets yourself, as I'm not including these in the public repo. They might be found in other repos of Deezer download tools. LastFM values can be made with your own LastFM account.

I am having issues finding keys and secrets. I wanted to try making refreezer available on windows, but without those it seems to be not worth trying anymore.
