### ISSUE TITLE
[Feature Request]  shuffling specific playlists and albums

### ISSUE THREAD

**Issue by lucasdaweb95** [DJDoubleD/refreezer#40]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**
shuffling specific albums and playlists

---

## **Describe the solution you'd like**
add a button to shuffle those

---

## **Describe alternatives you've considered**
not using shuffle (miserable experience)

---

**Comment by DJDoubleD** [comment]
I'm not sure I understand your question.
When you play a track from an album or a playlist, that respective album or playlist contents gets added to the player queue.
You can go the the player queue screen (on player screen, top right) and press the shuffle button to, well, shuffle.
You can also edit the queue by manually reordering (only when shuffle is disabled, press and hold track tile to drag to desired position) or removing tracks from the list.

Is this not the option you are looking for?

**Comment by lucasdaweb95** [comment]
What im looking for is a button to instantly shuffle a playlist and only that playlist, not the queue

**Comment by DJDoubleD** [comment]
But when you start a track from a playlist, the playlist will override the previous queue.
So shuffling the queue after starting a track from within, IS shuffling the playlist.

I guess you then just want a context menu option to directly shuffle the selected playlist instead going to the queue screen to shuffle it (and doing the exact same thing)?

**Comment by lucasdaweb95** [comment]
Thats weird, becuse when i tried it, it showed tracks outside of my playlist

**Comment by lucasdaweb95** [comment]
run a song, then press shuffle on the library.

**Comment by DJDoubleD** [comment]
> run a song, then press shuffle on the library.

The shuffle button in the main library screen, triggers the function to create a shuffled playing queue based on your entire favorites library.
It is literally the same function as the `Shuffle my music` button in the Deezer web player
![image](https://github.com/user-attachments/assets/85efef62-e4cd-44ba-b1dc-9eccf3f28180)

So again, please try this:
- Go to the playlist you whish to play shuffled and play a track
- In the player screen, open the queue (top right, queue will contain only tracks from the selected playlist)
- Press the shuffle button in the top right of the queue screen

Isn't this the behavior you are looking for?

**Comment by lucasdaweb95** [comment]
oooooh yeah...

**Comment by KelvinCrag** [comment]
> I guess you then just want a context menu option to directly shuffle the selected playlist instead going to the queue screen to shuffle it (and doing the exact same thing)?

Yes @DJDoubleD
