### ISSUE TITLE
[Feature Request] Clear queue

### ISSUE THREAD

**Issue by ghost** [DJDoubleD/refreezer#5]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**
Yah, can't clear the queue after a song finishes playing. Either loops or adds new ones. I don't like how Spotify does this either.

## **Describe the solution you'd like**
Like in Murgler 2, clear queue 'X' button or ability to remove now playing songs.

## **Describe alternatives you've considered**
I've tried manually removing (X-ing) the tracks in the queue, but it keeps inserting recommendations.

**Comment by DJDoubleD** [comment]
I'll look into adding a way to clear the current playing queue as alternative to removing tracks 1 by 1.
Although I do wonder, if you want to clear all tracks from the current playing queue AND don't want the app to load new tracks at the end of the queue, wouldn't that just mean you want to either pauze/exit the app or select a new queue source, in which case the entire current playing queue will be replaced anyway?
I do not really see the use-case for wanting to clear the entire queue AND not having the app load new tracks.

But the queue end behavior depends on the queue source.
When the source is any "smart playlist" (Flow, Radio, Mix, ..), it is the intended behavior for the app to keep getting tracks, just like Deezer does itself, as they are intended for continuous listening.
When the queue source is a normal playlist, the playlist is loaded in batches of 25 tracks (for performance) until the full playlist has been fetched and the queue ends, well..., at it's end (unless you set repeat mode).
For albums, podcasts, ..., the queue also just ends when all tracks of the respective item have played (again, depending on the selected repeat mode).

Could you please specify in which scenario the playing queue unexpectedly fetches more tracks?
Or do you mean that you want the option for the "smart playlists" to only fetch 1 batch of tracks and then stop?

**Comment by spftware** [comment]
> Could you please specify in which scenario the playing queue unexpectedly fetches more tracks?

oh, I simply didn't understand that there *was* an end to the Mix/Smart playlists. It seemed quite large and I assumed it kept adding more (similar to Spotify).

> wouldn't that just mean you want to either pauze/exit the app or select a new queue source, in which case the entire current playing queue will be replaced anyway?

when I exit the app, I prefer the queue to be cleared to start fresh when run again.

> I do not really see the use-case for wanting to clear the entire queue AND not having the app load new tracks.

It's more pedantic than a feature I guess

Or do you mean that you want the option for the "smart playlists" to only fetch 1 batch of tracks and then stop?

That particularly doesn't matter to me as a way to remove all playing tracks and have no song playing would be fine.
e.g.: I played a single song, it stopped but didn't clear the queue. When I removed the track, it didn't affect and still kept it as "in-queue" (paused but not actually playing).
