### ISSUE TITLE
[Bug] .mp3 file and .lrc file don't link while playing...

### ISSUE THREAD

**Issue by Dewt20** [DJDoubleD/refreezer#51]
# **🐞 Bug Report**

## **Describe the bug**
when the downloaded songs are playing lyrics don't show up. It means that the name of the .mp3 file doesn't match the name of the .lrc file. But they looks the same. Eventhough the both files happen have the same name, when playin they don't link together.->
---
![Screenshot_20241206-002342_MT Manager (1)](https://github.com/user-attachments/assets/4870bb87-9eea-4895-8abe-f419d5eb6487)

### **Is this a regression?**
I tried the previous version and it also had this issue. I also tried the old freezer app and it doesn't had this issue.

And I tried changing the name of the both downloaded files name into to a same name and it worked. Then lyrics showed up.
Ex:  name1.mp3    name1.lrc

But it's so much work to rename every song file and LRC file I downloaded.

This is how it supposed to look like when .mp3 and .lrc files are linked
![Screenshot_20241206-002510_Retro Music](https://github.com/user-attachments/assets/167e7dbd-d472-4d2b-b086-d8987ead65a6)

But this is how it looks now
![Screenshot_20241206-002526_Retro Music] 
(https://github.com/user-attachments/assets/3b1f106d-1fac-4024-9e6a-2e44c9a2a4b2)

Please fix this issue quickly..🥺🥺
If you need further info about this lag send me a email.
dewminatheekshana2006@gmail.com

**Comment by DJDoubleD** [comment]
Can you please include the url to the track that you used so I can try to reproduce this?

**Comment by Dewt20** [comment]
When I was playing this morning the lyrics were playing fine.
I downloaded some new songs and tried again. Then they didn't link together.
So I did a device restart to see wether it's a my problem. After that they
were linking finely. It was a issue with my phone at first.
Sorry to make a scene I'll delete the bug report..😄
