### ISSUE TITLE
[Bug] Flac 

### ISSUE THREAD

**Issue by diipeshk** [DJDoubleD/refreezer#52]
# **🐞 Bug Report**

## **Describe the bug**

*

---

### **Is this a regression?**

---

### **To Reproduce**

1.
2.
3.
4.

---

### **Expected behaviour**

*

---

### **Screenshots**

---

### **Additional context**

*

**Comment by DJDoubleD** [comment]
Either actually fill out the title and contents of the issue or I'll close/remove it as I can do nothing with just 1 word...
