### ISSUE TITLE
[Bug] Explicit words are not played

### ISSUE THREAD

**Issue by User-Loading** [DJDoubleD/refreezer#8]
# **🐞 Bug Report**

Most of the songs are auto censored meant as just not played but funny thing that the most explicit songs aren't, account is not set to hide that

*

---

First time so I don't know

---

### **To Reproduce**

1.Search a explicit song that is known
2. Play it
3. Listen and it just plays nothing until that word is over

---

### **Expected behaviour**
It plays it

### **Screenshots**
Audio so no screenshots

**Comment by DJDoubleD** [comment]
The app doesn't change anything to the tracks contents, they are streamed directly from the Deezer servers.
Please make sure that you are playing the Explicit version of  the track and that the account you are using has the explicit tracks allowed.

I have tried multiple explicit tracks and they all play the expected explicit content...
If you really think this is a problem, please provide concrete examples as I am unable to reproduce this.

**Comment by bw8686** [comment]
This issue is caused by Hide Explicit Content being enabled in your deezer account settings. Which either 1 means your account is marked as a child family account or you have that setting toggled in your deezer settings.

**Comment by User-Loading** [comment]
Okay I figured out it was just my account being broken a little bit, and the hide explicit content was disabled but deezer just didn't like that, logged in on a different device and solved


Sorry for bothering
